import { Request, Response, Router } from 'express';
import statusRouter from './statusRouter';
import clinicRouter from './clinicRouter';
import commentRouter from './commentRouter';
import doctorRouter from './doctorRouter';
import majorRouter from './majorRouter';
import postRouter from './postRouter';
import roleRouter from './roleRouter';
import scheduleRouter from './doctorScheduleRouter';
import serviceRouter from './servicesRouter';
import timeRouter from './timeRouter';
import userRouter from './userRouter';
import homeDirectoryRouter from './home_directoryRouter';
import homeMenuRouter from './home_menuRouter';
import appointmentRouter from './appointmentRouter';
import scheduleDetailRouter from './doctorScheduleDetailRouter';
import categoryServicesRouter from './category_servicesRouter';
import postCategoryRouter from './post_category';
import uploadRouter from './upload';
import patientProfileRouter from './patient_profileRouter';
import appointmentStatusRouter from './appointment_statusRouter';
import doctorScheduleRouter from './doctorScheduleRouter';
let appRouter = Router();
appRouter.use('/status', statusRouter);
appRouter.use('/appointment', appointmentRouter);
appRouter.use('/clinic', clinicRouter);
appRouter.use('/comment', commentRouter);
appRouter.use('/doctor', doctorRouter);
appRouter.use('/major', majorRouter);
appRouter.use('/post', postRouter);
appRouter.use('/role', roleRouter);
appRouter.use('/doctor-schedule', doctorScheduleRouter);
appRouter.use('/service', serviceRouter);
appRouter.use('/time', timeRouter);
appRouter.use('/user', userRouter);
appRouter.use('/home-directory', homeDirectoryRouter);
appRouter.use('/home-menu', homeMenuRouter);
appRouter.use('/schedule-details', scheduleDetailRouter);
appRouter.use('/category-services', categoryServicesRouter);
appRouter.use('/post-category', postCategoryRouter);
appRouter.use('/', uploadRouter);
appRouter.use('/patient-profile', patientProfileRouter);
appRouter.use('/appointment-status', appointmentStatusRouter);

export default appRouter;
